// Тут подключаются сторонние библиотеки (минифицированные) через gulp-file-include

@@include('../../node_modules/@babel/polyfill/dist/polyfill.min.js')
@@include('../../node_modules/jquery.browser/dist/jquery.browser.js')
@@include('../../node_modules/autosize/dist/autosize.js')
@@include('../../node_modules/jquery-ui/ui/core.js')
@@include('../../node_modules/jquery-ui/ui/widget.js')
@@include('../../node_modules/jquery-ui/ui/position.js')
// @@include('../../node_modules/jquery-ui/ui/mouse.js')
@@include('../../node_modules/jquery-ui/ui/menu.js');
@@include('../../node_modules/jquery-ui/ui/autocomplete.js')
@@include('../../node_modules/jquery-ui/ui/slider.js')
@@include('../../node_modules/jquery-ui/ui/datepicker.js')
@@include('../../node_modules/jquery-ui/ui/i18n/datepicker-ru.js')
@@include('../../node_modules/tippy.js/dist/tippy.min.js')
@@include('../../node_modules/focus-visible/dist/focus-visible.min.js')
@@include('../../node_modules/jquery.inputmask/dist/jquery.inputmask.bundle.js')
@@include('../../node_modules/select2/dist/js/select2.full.js')
@@include('../../node_modules/swiper/dist/js/swiper.min.js')
@@include('../../node_modules/lazysizes/lazysizes.min.js')
@@include('../../node_modules/parsleyjs/dist/parsley.js')
@@include('../../node_modules/parsleyjs/dist/i18n/ru.js')
@@include('../../node_modules/parsleyjs/dist/i18n/en.js')
